services:
    Overblog\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor:
        class: Overblog\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor
        public: false
        tags:
            - { name: overblog_graphql.definition_config_processor, priority: 2048 }

    Overblog\GraphQLBundle\Definition\ConfigProcessor\AclConfigProcessor:
        class: Overblog\GraphQLBundle\Definition\ConfigProcessor\AclConfigProcessor
        arguments:
            - '@overblog_graphql.access_resolver'
            - "%overblog_graphql.default_resolver%"
        public: false
        tags:
            - { name: overblog_graphql.definition_config_processor, priority: 512 }

    Overblog\GraphQLBundle\Definition\ConfigProcessor\FormConfigProcessor:
        class: Overblog\GraphQLBundle\Definition\ConfigProcessor\FormConfigProcessor
        public: false
        arguments:
            - "@Overblog\\GraphQLBundle\\Definition\\Builder\\FormDescriber"
        tags:
            - { name: overblog_graphql.definition_config_processor, priority: 512 }
